"""Build agents/hybrid_v1.py: a replayed meta opening followed by the plan_v1 planner.

The opening tape is the public router's main route (agents/public/tschinkel_router_v31.py,
Kaggle notebook by Thomas Tschinkel; behavioural provenance, see docs/strategy.md). Its actions
for steps [0, HANDOVER) are embedded verbatim with two repairs: a unit told to work a tile that
holds a weed digs it instead. (Sells are not clamped: same-turn PLACE/DROP feeds them.)

Usage: python scripts/build_hybrid.py [--handover 264] [--tape agents/public/tschinkel_router_v31.py]
"""
import argparse
import base64
import importlib.util
import json
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

WRAPPER = '''

# ============================================================ hybrid: replayed opening
HANDOVER = {handover}
_TAPE = json.loads(zlib.decompress(base64.b64decode(b"".join([
{blob}
]))).decode())
_TILE_OPS = {{"PLANT", "WATER", "HARVEST", "FERTILIZE", "FEED", "CARE", "COLLECT_FERTILIZER",
              "BUILD_COOP", "BUILD_PASTURE", "PLACE"}}


def _repair(obs, act):
    """Community repairs: dig a weed under a unit that was told to work that tile; clamp sells."""
    me = int(obs.get("player", 0))
    farm = obs["farms"][me]
    tiles = farm["tiles"]
    positions = [tuple(farm["farmer"])] + [tuple(h) for h in farm["hands"]]
    units = [list(act.get("farmer") or ["PASS"])] + [list(h) for h in (act.get("hands") or [])]
    units = (units + [["PASS"]] * len(positions))[:len(positions)]
    for i, (x, y) in enumerate(positions):
        t = tiles[y][x]
        if isinstance(t, dict) and t.get("kind") == "WEED" and units[i] and units[i][0] in _TILE_OPS:
            units[i] = ["DIG"]
    market = [list(o) for o in (act.get("market") or [])]  # the tape's orders are consistent by construction
    return {{"farmer": units[0], "hands": units[1:], "market": market[:MAX_ORDERS]}}


_HP = None


def agent(obs):
    global _HP
    try:
        step = int(obs.get("step", 0))
        if step == 0 or _HP is None:
            _HP = Planner()
        if step < HANDOVER and step < len(_TAPE):
            return _repair(obs, _TAPE[step])
        return _HP.act(obs)
    except Exception:
        try:
            hands = obs["farms"][int(obs.get("player", 0))].get("hands") or []
        except Exception:
            hands = []
        return {{"farmer": ["PASS"], "hands": [["PASS"] for _ in hands], "market": []}}
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--handover", type=int, default=264)
    ap.add_argument("--tape", default=str(ROOT / "agents" / "public" / "tschinkel_router_v31.py"))
    ap.add_argument("--out", default=str(ROOT / "agents" / "hybrid_v1.py"))
    args = ap.parse_args()

    spec = importlib.util.spec_from_file_location("tape", args.tape)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    route = mod.routes()[mod.MAIN][:args.handover]
    actions = [{"farmer": a.get("farmer") or ["PASS"], "hands": a.get("hands") or [],
                "market": a.get("market") or []} for a in route]
    blob = base64.b64encode(zlib.compress(json.dumps(actions).encode(), 9)).decode()
    blob_lines = ",\n".join('    b"%s"' % blob[i:i + 96] for i in range(0, len(blob), 96))

    src = (ROOT / "agents" / "plan_v1.py").read_text(encoding="utf-8")
    # drop plan_v1's own module-level agent wrapper; the hybrid defines its own last callable
    cut = src.index("\n_P = None")
    body = src[:cut]
    body = body.replace("import math\n", "import math\nimport json\nimport zlib\nimport base64\n", 1)
    body = body.replace('"""Kaggriculture agent, plan_v1:', '"""Kaggriculture agent, hybrid_v1 (generated by scripts/build_hybrid.py):\nreplayed meta opening for the first %d steps, then plan_v1:' % args.handover, 1)
    out = body + WRAPPER.format(handover=args.handover, blob=blob_lines)
    Path(args.out).write_text(out, encoding="utf-8")
    print("wrote", args.out, "steps in tape:", len(actions), "bytes:", len(out))


if __name__ == "__main__":
    main()
