const assert = require('node:assert/strict');
const path = require('node:path');
const {pathToFileURL} = require('node:url');
const {chromium} = require('C:/Users/xyygl/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async () => {
  const browser = await chromium.launch({headless:true,channel:'msedge'});
  const page = await browser.newPage({viewport:{width:1400,height:1100}});
  const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(pathToFileURL(path.resolve(__dirname,'../viz/dsm-tapes.html')).href);
  assert.equal(await page.locator('#board button').count(),100);
  const gameCount=Number(process.argv[2]||12);
  assert.equal(await page.locator('#game option').count(),gameCount);
  await page.locator('#viewer').waitFor({state:'visible'});
  assert.match(await page.locator('#orders').innerText(),/BUY_ANIMAL COW 1/);
  await page.locator('#next').click();
  assert.match(await page.locator('#clock').innerText(),/turn 1$/);
  await page.locator('#nextDay').click();
  assert.match(await page.locator('#clock').innerText(),/turn 25$/);
  await page.locator('#board button').nth(44).click();
  assert.equal(await page.locator('#tileTitle').innerText(),'Tile (4, 4)');
  await page.locator('#seek').fill('719');
  assert.equal(await page.locator('#orders').innerText(),'End of recorded game');
  await page.locator('#play').click();
  await page.waitForFunction(()=>!document.getElementById('clock').textContent.endsWith('turn 719'));
  await page.locator('#play').click();
  await page.locator('#side').selectOption('opponent');
  assert.match(await page.locator('#farmTitle').innerText(),/M & M & P & Q/);
  await page.locator('#filter').selectOption('loss');
  const lossCount=await page.locator('#game option').count();
  if(lossCount) assert.match(await page.locator('#game option').first().innerText(),/LOSS/);
  else assert.equal(await page.locator('#empty').isVisible(),true);
  await page.locator('#filter').selectOption('all');
  await page.locator('#viewer').waitFor({state:'visible'});
  await page.locator('#game').selectOption({index:1});
  await page.locator('#viewer').waitFor({state:'visible'});
  await page.locator('#side').selectOption('dsm');
  await page.locator('#seek').fill('360');
  for(const width of [1400,390]) {
    await page.setViewportSize({width,height:1100});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`overflow at ${width}`);
  }
  await page.setViewportSize({width:1400,height:1100});
  await page.screenshot({path:path.resolve(__dirname,'../viz/dsm-tapes-preview.png'),fullPage:true});
  assert.deepEqual(errors,[]);
  await page.locator('#game').selectOption({index:gameCount-1});
  await page.locator('#viewer').waitFor({state:'visible'});
  await page.locator('#game').selectOption({index:0});
  await page.locator('#viewer').waitFor({state:'visible'});
  assert.match(await page.locator('#orders').innerText(),/BUY_ANIMAL COW 1/);
  console.log(`Passed: ${gameCount}-game loading, stepping, end/restart playback, tile inspection, opponent, result filter, game switch/reload, mobile overflow, no browser errors.`);
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
