"""Convert compact leader recordings (data/leader_tapes/<team>_<submission>/*.json.gz: seed, 8 shops, both action
streams) into the tape-router builder's DSM tape format (data/dsm_tapes/<submission>/<episode>.json.gz, as
scripts/extract_dsm_tapes.py writes from raw replays): 31 day-start shop lists, 30 day-start boards (10 row strings of
2-char labels, weeds ' w'), cash (30), actions (719), hands_by_step (720), opp_actions. Everything is regenerated by an
exact replay; the replay must reproduce both recorded cash totals.

usage: convert_leader_tapes_20260929.py --src data/leader_tapes/16732748_56619023 --sub 56619023"""
import argparse
import gzip
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import upkeep_engine as UE  # noqa: E402
from extract_mg_events import tile_label  # noqa: E402


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True)
    ap.add_argument("--sub", required=True)
    a = ap.parse_args()
    out = ROOT / "data/dsm_tapes" / a.sub
    out.mkdir(parents=True, exist_ok=True)
    ok = n = 0
    for p in sorted((ROOT / a.src).glob("*.json.gz")):
        x = json.load(gzip.open(p, "rt", encoding="utf-8"))
        seat = int(x["seat"])
        w = UE.World(x["seed"], x["shops"])
        boards, cash, hands, shops = [], [], [], []
        for t in range(719):
            if t % 24 == 0:
                f = w.farms[seat]
                boards.append(["".join(tile_label(c).rjust(2) for c in row) for row in f["tiles"]])
                cash.append(f["money"])
                shops.append(list(w.state[0].observation["town"]["unlocked_shops"]))
            hands.append(len(w.farms[seat]["hands"]))
            acts = [UE.tape_action(x["actions"], t), UE.tape_action(x["opp_actions"], t)]
            w.step(acts if seat == 0 else acts[::-1])
        hands.append(len(w.farms[seat]["hands"]))
        shops.append(list(w.state[0].observation["town"]["unlocked_shops"]))
        final = [w.farms[0]["money"], w.farms[1]["money"]]
        match = [round(v) for v in final] == [round(v) for v in x["rewards"]]
        n += 1
        ok += match
        if not match:
            print("cash mismatch", x["episode"], final, x["rewards"])
            continue
        rec = dict(episode=x["episode"], submission=a.sub, seat=seat, seed=x["seed"], rewards=x["rewards"], shops=shops[:31],
                   boards=boards[:30], cash=cash[:30], actions=x["actions"], hands_by_step=hands[:720],
                   opp_actions=x["opp_actions"])
        (out / f"{x['episode']}.json.gz").write_bytes(gzip.compress(json.dumps(rec).encode(), mtime=0))
    print(f"{n} recordings, {ok} reproduce both cash totals -> {out}")


if __name__ == "__main__":
    main()
