"""Summarize frozen midgame experiments and verify the deployable local wrapper."""
from collections import defaultdict
from copy import deepcopy
import json
import random
from statistics import mean
from pathlib import Path
from evaluate_boards import ROOT,module_at,observation

OUT=ROOT/'results/fresh/midgame'


def main():
    stages={s:json.loads((OUT/f'{s}.json').read_text()) for s in ('audit','audit2','train','refine','validate','test','endgame')}
    selected=json.loads((OUT/'selection.json').read_text());name=selected['name']
    splits=json.loads((OUT/'splits.json').read_text())['splits']
    seed=splits['test'][0]['seed'];verified=0
    for seat in (0,1):
        replay=json.loads((OUT/f'test-{name}-{seed}-seat{seat}-router-None/replay.json').read_text())
        agent=module_at('verify_selected_mid',ROOT/'agents/midgame_selected.py')
        for t in range(719):
            obs=observation(replay['steps'][t],seat);before=deepcopy(obs)
            assert agent.agent(obs)==replay['steps'][t+1][seat]['action'],(seat,t)
            assert obs==before
            verified+=1
    lines=['# Midgame research: maintenance, investment, and conditional routing','',
           f"Validation-selected policy: **{name}**. Local wrapper: `agents/midgame_selected.py`. Selection was frozen before test results. None of the new controllers passed promotion; retain the full conditional public router.",'',
           '## Design','',
           'Every game starts from a saved day-9 checkpoint generated by two independent copies of the public router. The same root is restored for each candidate; the original seed continues throughout. No shops are overridden. Both router instances are warmed on the recorded prefix, with exact action checks. The full opponent retains all branches: Yarn Store at step 226, carrot price at 360, and milk inventory at 433.','',
           'Frozen cohorts: 16 training seeds, 8 validation seeds, 16 untouched test seeds. Each cohort is balanced by whether any Yarn Store is visible at day 9. Root selection uses those already-observed shops only, not later outcomes. This is a balanced stress panel rather than an estimate weighted to the natural frequency of shop conditions. Validation and test use both seats and both full-router and legacy-maintenance opponents. Seats from the same root are related observations.','',
           'The first grid varies additional herd {none, four cows, four sheep}, staff cap {10,14}, and fertilizer {sell, apply}: 12 configurations, plus full-router, no-branch-router and legacy controls. Refinement varies crop allocation (carrot, tomato, strawberry), land expansion, reserves, investment cutoff and sale-price floor around the strongest new training configuration. A conditional selector chooses at day 9 using visible Yarn Store presence, with shop-specific scores shrunk 50% toward global scores.','',
           '## Maintenance audit','',
           '| Version / policy | Mean cash | Mean margin vs full router | Mean premature crop losses | Mean animal losses |','|---|---:|---:|---:|---:|']
    for stage,policy in (('audit','legacy'),('audit','service-10'),('audit2','service-10'),('audit2','service-14'),('audit2','router')):
        g=[r for r in stages[stage] if r['name']==policy]
        lines.append(f"| {stage} / {policy} | {mean(r['cash'] for r in g):,.0f} | {mean(r['margin'] for r in g):+,.0f} | {mean(r['diagnostics'][r['seat']].get('premature_crop_losses',0) for r in g):.1f} | {mean(r['diagnostics'][r['seat']].get('animal_losses',0) for r in g):.1f} |")
    lines += ['','The new controller prioritizes survival deadlines, projects only our legal actions to prevent duplicate resource use, collects feed in larger batches, and sends stock back before overflow. The initial version over-prioritized optional watering; the revised version prioritizes harvest/replanting and accounts for pending planting in staffing. Surviving assets did not by itself close the router’s income advantage. Detailed action/no-effect/overflow counters are in the audit summaries.','',
              'Premature crop deaths exclude normal expiry and do not measure all lost harvest yield. Animal losses include late escapes, which can reflect a deliberate decision to stop feeding. Zero losses alone is not an economic success criterion.','',
              'Across these four audit seeds, the router sold 260.2 strawberries on average versus 79.5 for service-14, while spending 5,325 on wages versus 6,190. These are different production systems: the router also expands and replants premium crops. The figures identify a production gap, not a pure causal estimate of routing efficiency.','',
              '## Untouched practical test','',
              '| Policy | Opponent | Our cash | Opponent cash | Margin | Wins / draws / losses |','|---|---|---:|---:|---:|---:|']
    for n in sorted({r['name'] for r in stages['test']}):
        for opponent in ('router','legacy'):
            g=[r for r in stages['test'] if r['name']==n and r['opponent']==opponent]
            lines.append(f"| {n} | {opponent} | {mean(r['cash'] for r in g):,.0f} | {mean(r['opponent_cash'] for r in g):,.0f} | {mean(r['margin'] for r in g):+,.0f} | {sum(r['margin']>0 for r in g)} / {sum(r['margin']==0 for r in g)} / {sum(r['margin']<0 for r in g)} |")
    lookup={(r['name'],r['seed'],r['seat'],r['opponent']):r for r in stages['test']}
    rng=random.Random(204001)
    for n in sorted({r['name'] for r in stages['test']} - {'router'}):
        seed_diffs=defaultdict(list)
        for r in stages['test']:
            if r['name']==n:
                b=lookup['router',r['seed'],r['seat'],r['opponent']]
                seed_diffs[r['yarn'],r['seed']].append(r['margin']-b['margin'])
        strata=[[mean(v) for (y,s),v in seed_diffs.items() if y==wanted] for wanted in (False,True)]
        boot=sorted(mean(mean(rng.choices(v,k=len(v))) for v in strata) for _ in range(4000))
        lines += ['',f"{n} minus full-router policy: mean paired margin change {mean(mean(v) for v in strata):+,.0f}; descriptive 95% stratified seed-bootstrap interval [{boot[100]:+,.0f}, {boot[3899]:+,.0f}]. Seats and opponents are averaged within each seed before resampling."]
    lines += ['','## Conditional-router contribution (test)','','| Day-9 context | Full-router margin | No-branch-router margin |','|---|---:|---:|']
    for yarn in (False,True):
        values=[mean(r['margin'] for r in stages['test'] if r['name']==n and r['opponent']=='router' and r['yarn']==yarn) for n in ('router','no-branches')]
        lines.append(f"| {'Yarn present' if yarn else 'No Yarn'} | {values[0]:+,.0f} | {values[1]:+,.0f} |")
    lines += ['','## Common endgame sensitivity (validation roots)','','Both players switch to the same maintenance/liquidation controller at the indicated day. This removes native-router decisions after the boundary; it is a component test, not the practical full-router matchup above.','','| Policy | Endgame starts | Mean margin |','|---|---:|---:|']
    for n in sorted({r['name'] for r in stages['endgame']}):
        for d in (22,24,26):
            g=[r for r in stages['endgame'] if r['name']==n and r['end_day']==d]
            lines.append(f"| {n} | {d} | {mean(r['margin'] for r in g):+,.0f} |")
    for stage in ('train','refine','validate'):
        lines += ['',f'## {stage.title()} ranking','','| Policy | Mean cash | Mean margin |','|---|---:|---:|']
        rows=stages[stage]
        for n in sorted({r['name'] for r in rows},key=lambda n:-mean(r['margin'] for r in rows if r['name']==n)):
            g=[r for r in rows if r['name']==n]
            lines.append(f"| {n} | {mean(r['cash'] for r in g):,.0f} | {mean(r['margin'] for r in g):+,.0f} |")
    lines += ['','## Frozen selection','','```json',json.dumps(selected,indent=2),'```','','## Checks and limits','',
              f"{sum(len(r) for r in stages.values())} completed games across the reported stages. All completed with valid intermediate statuses and exact continuation cash reconciliation. {verified} full-game decisions reproduced through the selected wrapper without observation mutation. Engine tests verify fertilizer-before-water yield and urgent watering, and explicitly check both cow and sheep target increments.",'',
              'An initial status-check error was corrected before audit reporting. An initial training run had a cow-target configuration-key error and was excluded; its outputs and original controller are retained separately. The corrected grid was rerun in full. Manifests preserve the source hashes and exact scenarios for each stage.','',
              'This remains a small, two-opponent panel. Comparisons between configurable policies hold the execution controller constant; comparison with the router also includes route quality. The adaptive model uses only Yarn Store presence at the checkpoint, not a full demand forecast or continuous replanning. Randomized mixtures were not tested. The deployment wrapper requires local project files and the installed game engine; it is not a standalone submission.','',
              f"[Selected full replay](../results/fresh/midgame/test-{name}-{seed}-seat0-router-None/replay.json) · [Frozen scenario cohorts](../results/fresh/midgame/splits.json)",'',
              'Reproduction: `scripts/research_midgame.py --stage roots|audit2|train|refine|validate|test|endgame`. Between stages run `scripts/select_midgame.py --stage refine|shortlist|select` respectively. Simulation stages checkpoint results and check source/scenario hashes on resume.','']
    (ROOT/'docs/midgame_research.md').write_text('\n'.join(lines),encoding='utf-8')
    print('PASS',verified,'reproduced actions; selected',name)
    for opponent in ('router','legacy'):
        g=[r for r in stages['test'] if r['name']==name and r['opponent']==opponent]
        print(name,'vs',opponent,'cash',mean(r['cash'] for r in g),'opponent',mean(r['opponent_cash'] for r in g),'margin',mean(r['margin'] for r in g))


if __name__=='__main__':main()
