"""Router-4Q tape extraction (2026-09-30): a copy of scripts/convert_leader_tapes_20260929.py with a NEW output folder.

Converts compact leader recordings (data/leader_tapes/<team_id>_<submission>/*.json.gz: seed, 8 shops, both action
streams) into the tape-router builder's tape format (the data/dsm_tapes schema that scripts/build_mg_tape_agent.py reads):
31 day-start shop lists, 30 day-start boards (10 row strings of 2-char labels, weeds ' w'), cash (30), actions (719),
hands_by_step (720), opp_actions. Everything is regenerated by an exact official-engine replay (scripts/upkeep_engine.py,
recorded seed, forced shops, both seats' recorded commands); the replay must reproduce both recorded cash totals, games
that do not are skipped (listed).

Added for the 4Q opening fidelity check (fields the builder ignores): quadrants (30, day-start owned quadrants),
hands (30, day-start hand count), fail_by_day (30 x {buy_cash, hire, land}: the leader's own market orders that failed in
its real game - leaders over-request hires on purpose), team, team_id.

Output: data/leader_semantics_router4q/<team_id>_<submission>/<episode>.json.gz (never an existing data folder).

usage: router4q_convert_20260930.py 16732748_56692773[,16681125_56679033,...] [--limit N]"""
import gzip
import json
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import upkeep_engine as UE  # noqa: E402
from extract_mg_events import tile_label  # noqa: E402

SRC = ROOT / "data/leader_tapes"
OUT = ROOT / "data/leader_semantics_router4q"


def convert(p, team, team_id, sub):
    x = json.load(gzip.open(p, "rt", encoding="utf-8"))
    seat = int(x["seat"])
    w = UE.World(x["seed"], x["shops"])
    E = w.E
    day_box = [0]
    fails = [dict(buy_cash=0, hire=0, land=0) for _ in range(30)]
    o_commit, o_hire, o_land = E._commit_unit, E._do_hire, E._do_buy_land

    def is_leader(farm):
        return farm is w.state[0].observation["farms"][seat]

    def commit(op, item, price, farm, private, market, shed_capacity=100):
        ok = o_commit(op, item, price, farm, private, market, shed_capacity)
        if not ok and op != "SELL" and is_leader(farm) and farm["money"] < price:
            fails[day_box[0]]["buy_cash"] += 1
        return ok

    def hire(farm, private, board_size, mult=1):
        n = len(farm["hands"])
        o_hire(farm, private, board_size, mult)
        if is_leader(farm) and len(farm["hands"]) == n:
            fails[day_box[0]]["hire"] += 1

    def land(farm, board_size):
        n = len(farm["unlocked_quadrants"])
        o_land(farm, board_size)
        if is_leader(farm) and len(farm["unlocked_quadrants"]) == n and n < 4:
            fails[day_box[0]]["land"] += 1

    E._commit_unit, E._do_hire, E._do_buy_land = commit, hire, land
    try:
        boards, cash, hands, shops, quads, hands_day = [], [], [], [], [], []
        for t in range(719):
            day_box[0] = min(29, t // 24)
            if t % 24 == 0:
                f = w.farms[seat]
                boards.append(["".join(tile_label(c).rjust(2) for c in row) for row in f["tiles"]])
                cash.append(f["money"])
                quads.append(len(f["unlocked_quadrants"]))
                hands_day.append(len(f["hands"]))
                shops.append(list(w.state[0].observation["town"]["unlocked_shops"]))
            hands.append(len(w.farms[seat]["hands"]))
            acts = [UE.tape_action(x["actions"], t), UE.tape_action(x["opp_actions"], t)]
            w.step(acts if seat == 0 else acts[::-1])
        hands.append(len(w.farms[seat]["hands"]))
        shops.append(list(w.state[0].observation["town"]["unlocked_shops"]))
        final = [w.farms[0]["money"], w.farms[1]["money"]]
    finally:
        E._commit_unit, E._do_hire, E._do_buy_land = o_commit, o_hire, o_land
    match = [round(v) for v in final] == [round(v) for v in x["rewards"]]
    rec = dict(episode=x["episode"], submission=sub, team=team, team_id=team_id, seat=seat, seed=x["seed"],
               names=x.get("names"), rewards=x["rewards"], shops=shops[:31], boards=boards[:30], cash=cash[:30],
               quadrants=quads[:30], hands=hands_day[:30], fail_by_day=fails, actions=x["actions"],
               hands_by_step=hands[:720], opp_actions=x["opp_actions"], cash_match=match, final_cash=final)
    return match, rec


def main():
    a = sys.argv[1:]
    dirs = a[0].split(",")
    limit = int(a[a.index("--limit") + 1]) if "--limit" in a else None
    for d in dirs:
        team_id, sub = d.split("_")
        idx = json.loads((SRC / d / "index.json").read_text(encoding="utf-8"))
        team = idx.get("team", team_id)
        out = OUT / d
        out.mkdir(parents=True, exist_ok=True)
        files = sorted((SRC / d).glob("*.json.gz"))
        if limit:
            files = files[:limit]
        ok = n = skipped = 0
        t0 = time.time()
        for p in files:
            dst = out / p.name
            if dst.exists():
                skipped += 1
                continue
            n += 1
            try:
                match, rec = convert(p, team, int(team_id), sub)
            except Exception as exc:  # one broken recording must not stop the folder
                print("FAILED", d, p.name, repr(exc), flush=True)
                continue
            if not match:
                print("cash mismatch", d, rec["episode"], rec["final_cash"], rec["rewards"], flush=True)
                (out / ("mismatch_" + p.name[:-8] + ".txt")).write_text(json.dumps(dict(final=rec["final_cash"], rewards=rec["rewards"])))
                continue
            ok += 1
            dst.write_bytes(gzip.compress(json.dumps(rec).encode(), mtime=0))
        print(f"{d}: {n} converted now ({skipped} already there), {ok} reproduce both cash totals, "
              f"{time.time() - t0:.0f} s -> {out}", flush=True)


if __name__ == "__main__":
    main()
