import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'..'), out=path.join(root,'results/fresh/all_umg_m1');
const read=p=>JSON.parse(fs.readFileSync(p,'utf8')), sum=(a,f)=>a.reduce((n,x)=>n+f(x),0),species=['COW','SHEEP','GOOSE'];
const targets=['56266758','56266899'].flatMap(sub=>fs.readdirSync(path.join(root,'data/mg_tapes',sub)).filter(f=>f.endsWith('.json.gz')).map(f=>JSON.parse(zlib.gunzipSync(fs.readFileSync(path.join(root,'data/mg_tapes',sub,f))))));
const games=targets.filter(g=>fs.existsSync(path.join(out,'animals',`${g.episode}.json`))).map(g=>({...read(path.join(out,'animals',`${g.episode}.json`)),rating:g.rating,opponent:g.opponent}));
const animals=games.flatMap(g=>g.animals),purchases=games.flatMap(g=>g.purchases);
for(const a of animals){a.termination_censored=a.last_feed_day===29;if(a.termination_censored||a.last_feed_day===null)a.termination_day=null;}
assert.equal(new Set(targets.map(g=>g.episode)).size,targets.length);
const previous=read(path.join(root,'results/fresh/umg_lifecycles/feed_termination.json'));
let priorAnimalsChecked=0;
for(const a of previous.animals){const b=animals.find(b=>b.episode===a.episode&&b.animal===a.animal&&b.x===a.tile[0]&&b.y===a.tile[1]&&b.placed_day===a.placed_day);if(!games.some(g=>g.episode===a.episode))continue;assert(b);assert.deepEqual(b.feed_days,a.feed_days);assert.equal(b.last_feed_day,a.last_feed_day);assert.equal(b.departure_day,a.departure_day);priorAnimalsChecked++;}
const prevPurchases=read(path.join(root,'results/fresh/umg_lifecycles/animal_date_distributions.json'));
for(const p of prevPurchases.purchases){if(!games.some(g=>g.episode===p.episode))continue;assert(purchases.some(b=>b.episode===p.episode&&b.step===p.step&&b.animal===p.animal&&b.units===p.units));}
const summary={};
for(const s of species){const a=animals.filter(a=>a.animal===s),buys=purchases.filter(p=>p.animal===s);summary[s]={animals:a.length,purchases:sum(buys,p=>p.units),neverFed:a.filter(a=>a.last_feed_day===null).length,fedThroughFinalDay:a.filter(a=>a.termination_censored).length,survivors:a.filter(a=>a.departure_day===null).length,latePurchases:sum(buys.filter(p=>p.day>=18),p=>p.units),latestPurchase:Math.max(...buys.map(p=>p.day)),latestPlacement:Math.max(...a.map(p=>p.placed_day)),
 daily:Array.from({length:30},(_,d)=>({day:d,purchased:sum(buys.filter(p=>p.day===d),p=>p.units),placed:a.filter(a=>a.placed_day===d).length,lastFeed:a.filter(a=>a.last_feed_day===d).length,termination:a.filter(a=>a.termination_day===d).length,departed:a.filter(a=>a.departure_day===d).length,gamesBuying:new Set(buys.filter(p=>p.day===d).map(p=>p.episode)).size}))};}
const metadata=read(path.join(out,'m1_ratings.json')),team=new Map(metadata.teams.map(t=>[t.id,t.teamName]));
const episodes=metadata.episodes.filter(e=>e.state==='COMPLETED'&&e.agents.length===2&&e.agents.filter(a=>a.submissionId===56395605).length===1).map(e=>{const own=e.agents.find(a=>a.submissionId===56395605),opp=e.agents.find(a=>a.submissionId!==56395605);return {episode:e.id,created:e.createTime,ours:own.reward,rival:opp.reward,margin:own.reward-opp.reward,opponent:team.get(opp.teamId),rating:opp.initialScore??null,opponentSubmission:opp.submissionId};});
const allLoss=episodes.filter(e=>e.margin<0),losses=[];
for(const e of allLoss){const p=path.join(out,'losses',`${e.episode}.json`);if(!fs.existsSync(p))continue;const g={...read(p),...e};
 g.spend=sum(Object.values(g.economies[0].spend),x=>x);g.rivalSpend=sum(Object.values(g.economies[1].spend),x=>x);g.costEffect=g.rivalSpend-g.spend;
 assert(Math.abs(sum(g.products,p=>p.revenue_gap)+g.costEffect-g.margin)<1e-6);
 for(const p of g.products){const animal={MILK:'COW',WOOL:'SHEEP',EGG:'GOOSE'}[p.product];const keys=[`BUY_PRODUCT:${p.product}`,`BUY_SEED:${p.product}`,...(animal?[`BUY_ANIMAL:${animal}`]:[])];p.direct_cost=keys.reduce((n,k)=>n+(g.economies[0].spend[k]||0),0);p.rival_direct_cost=keys.reduce((n,k)=>n+(g.economies[1].spend[k]||0),0);p.direct_cash_gap=p.revenue_gap+p.rival_direct_cost-p.direct_cost;}
 g.sharedCostEffect=['HIRE','BUY_LAND'].reduce((n,k)=>n+(g.economies[1].spend[k]||0)-(g.economies[0].spend[k]||0),0);
 assert(Math.abs(sum(g.products,p=>p.direct_cash_gap)+g.sharedCostEffect-g.margin)<1e-6);
 const sorted=g.products.toSorted((a,b)=>a.direct_cash_gap-b.direct_cash_gap);g.top=sorted[0];
 g.shortfalls=g.products.filter(p=>!['WHEAT','FERTILIZER'].includes(p.product)&&p.ours.produced+10<p.opponent.produced&&p.quantity_component<-1000&&Math.max(p.ours.avg_price||0,p.opponent.avg_price||0)>=p.base);
 g.gluts=g.products.filter(p=>!['WHEAT','FERTILIZER'].includes(p.product)&&p.ours.low_harvest>=20&&p.ours.low_harvest>=p.ours.produced/2);
 g.deadCount=sum(Object.values(g.no_effect[0]),x=>x);g.commandCount=sum(Object.values(g.commands[0]),x=>x);
 const planPath=path.join(out,'plans',`${e.episode}.json`);g.plan=fs.existsSync(planPath)?read(planPath):null;
 if(g.plan){const h=g.plan.history;g.plan.lastSwitch=h.filter((x,i)=>i===0||x[1]!==h[i-1][1]).at(-1)?.[0]??null;g.plan.shopMismatch=Object.keys(Object.fromEntries([...g.plan.actualShops,...(g.plan.donor?.shops||[])].map(s=>[s,1]))).map(s=>({shop:s,actual:g.plan.actualShops.filter(x=>x===s).length,donor:(g.plan.donor?.shops||[]).filter(x=>x===s).length})).filter(x=>x.actual!==x.donor);}
 const top=g.top;g.reason=`${top.product}: direct cash gap ${Math.round(top.direct_cash_gap)} (revenue ${Math.round(top.revenue_gap)}); sold ${top.ours.sold} vs ${top.opponent.sold}, average ${top.ours.avg_price?.toFixed(1)??'n/a'} vs ${top.opponent.avg_price?.toFixed(1)??'n/a'}`;
 g.under2500=e.rating!==null&&e.rating<2500;
 losses.push(g);
}
losses.sort((a,b)=>Number(b.under2500)-Number(a.under2500)||a.margin-b.margin);
const stats={games:episodes.length,wins:episodes.filter(e=>e.margin>0).length,ties:episodes.filter(e=>e.margin===0).length,losses:allLoss.length,audited:losses.length,lossesUnder2500:allLoss.filter(e=>e.rating!==null&&e.rating<2500).length,auditedUnder2500:losses.filter(g=>g.under2500).length,missingRating:allLoss.filter(g=>g.rating===null).length};
stats.plansTraced=losses.filter(g=>g.plan).length;stats.actionMismatchGames=losses.filter(g=>g.plan?.mismatch.length).length;
stats.failedHires=sum(losses,g=>g.hires?.[0].failed||0);
const groups={};for(const [label,selected]of[['All losses',losses],['Opponent below 2500',losses.filter(g=>g.under2500)]]){groups[label]={games:selected.length,shortfallGames:selected.filter(g=>g.shortfalls.length).length,glutGames:selected.filter(g=>g.gluts.length).length,
 products:['CARROT','TOMATO','STRAWBERRY','MELON','EGG','MILK','WOOL','WHEAT','FERTILIZER'].map(product=>{const ps=selected.map(g=>g.products.find(p=>p.product===product));return {product,directCashGap:sum(ps,p=>p.direct_cash_gap),revenueGap:sum(ps,p=>p.revenue_gap),quantityGap:sum(ps,p=>p.quantity_component),priceGap:sum(ps,p=>p.price_component),sold:sum(ps,p=>p.ours.sold),lowSales:sum(ps,p=>p.ours.low_sales),floorSales:sum(ps,p=>p.ours.floor_sales),discarded:sum(ps,p=>p.ours.discarded),topDeficitGames:selected.filter(g=>g.top.product===product).length,shortfallGames:selected.filter(g=>g.shortfalls.some(p=>p.product===product)).length,glutGames:selected.filter(g=>g.gluts.some(p=>p.product===product)).length};})};}
const result={animalGames:games.length,targetAnimalGames:targets.length,missingAnimalGames:targets.filter(g=>!games.some(x=>x.episode===g.episode)).map(g=>g.episode),games,animals,purchases,summary,stats,episodes,losses,groups,missingLosses:allLoss.filter(e=>!losses.some(g=>g.episode===e.episode))};
result.ratingsSnapshotAt=fs.statSync(path.join(out,'m1_ratings.json')).mtime.toISOString();
result.validation={priorAnimalsChecked,exactLedgerFeedSegments:sum(games,g=>g.ledger_feed_checks),allLossCashAndStockLedgersReconcile:true,allLossActionStreamsMatch:stats.actionMismatchGames===0&&stats.plansTraced===stats.losses};
fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify(result));
let md=`# All UMG animal tapes and mgt_m1 loss audit\n\nCoverage: ${games.length}/${targets.length} existing UMG library tapes (submissions 56266758 and 56266899); ${losses.length}/${allLoss.length} losses in ${episodes.length} completed public mgt_m1 games (submission 56395605), as listed on 2026-09-22. ${stats.lossesUnder2500} losses faced opponents rated below 2500 at match time. The submission API listing is the observable history, not a guarantee of unbounded archived history.\n\n## Animal dates\n\nZero-based game days. Successful purchases count units; feed termination is the day after the final successful feed, including animals surviving the season. Dates alone do not prove deliberate retirement. Purchases cannot be uniquely matched to individual stored animals, so purchase events and animal placement/feed histories are separate.\n\n| Species | Placed | Purchased D18+ | Latest purchase | Latest placement | Final feed D27 | Final feed D28 |\n|---|---:|---:|---:|---:|---:|---:|---:|\n`;
for(const s of species){const x=summary[s];md+=`| ${s} | ${x.animals} | ${x.latePurchases} | ${x.latestPurchase} | ${x.latestPlacement} | ${x.daily[27].lastFeed} | ${x.daily[28].lastFeed} |\n`;}
md+=`\nFed through D29, with termination unobserved: ${species.map(s=>`${s} ${summary[s].fedThroughFinalDay}`).join(', ')}. Those termination cells are blank, not an asserted D30 stop.\n`;
md+='\n## Loss mechanisms\n\nBoth seats are replayed using recorded actions, the official engine, and the recorded shop schedule. Both final cash results and revenue/spend ledgers must match. Every product revenue gap is exactly decomposed into quantity and realized-price components: ΔQ × mean(P) + ΔP × mean(Q). These are descriptive accounting components, not profits achievable by changing one crop. If one seat sells zero, its comparison price is set to the other seat’s realized average, allocating the gap to quantity.\n\nA high-price production shortfall screen requires at least 11 fewer produced units, a quantity-component deficit over 1000, and either player’s realized average at least the product’s base price. A low-price production screen requires at least 20 units and at least half our harvested output harvested while the marginal quote was ≤25% of base. Wheat and fertilizer are excluded from these opportunity screens because they are inputs/byproducts. Low sales are measured separately at each actual execution price.\n\n';
md+='Direct cash gaps subtract product purchases, seeds and the associated animal purchases from revenue. Hired labor and land stay in a separate shared-cost bucket. These accounting buckets sum exactly to the cash margin; wheat feed cost stays in wheat and fertilizer input cost stays in fertilizer, so they are not stand-alone enterprise profits. This avoids misclassifying large wheat buy/resell turnover as farm underproduction.\n\n';
for(const[label,g]of Object.entries(groups)){md+=`### ${label}\n\n${g.games} audited; ${g.shortfallGames} meet a high-price production-shortfall screen; ${g.glutGames} meet a low-price production screen (categories overlap).\n\n| Product | Direct cash gap | Revenue gap | Quantity component | Price component | Biggest deficit in games | High-price shortfalls | Low-price production games |\n|---|---:|---:|---:|---:|---:|---:|---:|\n`;for(const p of g.products)md+=`| ${p.product} | ${Math.round(p.directCashGap)} | ${Math.round(p.revenueGap)} | ${Math.round(p.quantityGap)} | ${Math.round(p.priceGap)} | ${p.topDeficitGames} | ${p.shortfallGames} | ${p.glutGames} |\n`;}
md+=`\n## Execution and routing\n\nArchived m1 decisions were regenerated on reconstructed observations in ${stats.plansTraced} losing games; ${stats.actionMismatchGames} games have any mismatch with recorded actions. This separates a reproducible policy decision from a crash/fallback explanation. Detailed final-donor shop counts and last-switch dates are retained for each loss. Shop mismatch alone does not prove that a feasible better tape existed.\n\n`;
md+=`Across the ${losses.length} losses, ${stats.failedHires} HIRE requests within the engine's order limit failed. Thus these losses do not reproduce the earlier missing-worker hiring bug.\n\n`;
const below=losses.filter(g=>g.under2500),traced=below.filter(g=>g.plan);
md+=`Of ${traced.length} traced losses below 2500, ${traced.filter(g=>g.plan.shopMismatch.length).length} finish on a donor with different final shop counts; ${traced.filter(g=>g.plan.lastSwitch<=15).length} last switched by D15. This is consistent with a production plan that becomes hard to adapt as more demand is revealed, but a loss-only cohort does not establish that mismatch predicts losing. Below 2500, m1 spent ${sum(below,g=>(g.economies[0].spend.HIRE||0)-(g.economies[1].spend.HIRE||0))} more on hired labor in aggregate, and spent more in ${below.filter(g=>(g.economies[0].spend.HIRE||0)>(g.economies[1].spend.HIRE||0)).length} games.\n\n## Concrete failure examples\n\n`;
for(const eid of [111262874,111642811,111487784,111678108,111743130,112109339]){const g=losses.find(g=>g.episode===eid);if(!g)continue;md+=`- **${eid}, seed ${g.seed}, ${g.opponent} (${g.rating.toFixed(1)}): margin ${g.margin}.** ${g.reason}. `;if(g.gluts.length)md+=g.gluts.map(p=>`${p.product}: ${p.ours.low_harvest}/${p.ours.produced} units harvested at ≤25% of base`).join('; ')+'. ';if(g.plan)md+=`Last donor switch D${g.plan.lastSwitch}; differences: ${g.plan.shopMismatch.map(x=>`${x.shop} ${x.actual} actual / ${x.donor} donor`).join(', ')}. `;md+=`Shared labor/land contribution to margin: ${g.sharedCostEffect}.\n`;}
md+='\nThe largest overall loss, 112109339, combines a wool revenue deficit with 12,363 extra hired-labor expense (16,668 versus 4,305); its 25 units of discarded wool and lower average wool price also matter. This is not explained by underproduction alone. In 111743130, the opponent bought thousands of wheat units for resale: comparing gross wheat revenue would give a misleading main cause; subtracting purchases exposes wool as the largest direct cash deficit.\n\n## Implications for best-fit tape selection\n\n1. Rank feasible plans by their incremental product quantities over the remaining season, using expected residual demand after both players’ supply and the game’s nonlinear price curve. Final shop-count distance and raw sale volume are incomplete proxies.\n2. Give wool and strawberry output gaps priority when observed prices/demand support them. Their lead times mean a late need may require earlier cohort choices; do not assume a new sheep or strawberry root can fix the last few days.\n3. Penalize maintaining milk/wool capacity whose next yields will arrive into a glut, but include fertilizer byproducts, wheat feed and shared labor before retiring animals. A positive low-price sale from already-produced stock is not itself a mistake.\n4. Preserve animal age, crop maturity, inventory and feasible staffing when switching. A hindsight closer donor can fail if its expected mature herd or roots do not exist on our board.\n5. Validate any proposed change on both wins and losses in fresh games against responsive opponents. The observed gaps establish what differed; they do not establish the gain from a replacement policy.\n\n## Every loss, prioritized below 2500\n\n| Episode / seed | Opponent / match rating | Cash margin | Main product gap | Other high-price shortfalls | Low-price production |\n|---|---|---:|---|---|---|\n';
for(const g of losses)md+=`| ${g.episode} / ${g.seed} | ${g.opponent} / ${g.rating?.toFixed(1)??'unknown'} | ${g.margin} | ${g.reason} | ${g.shortfalls.map(p=>p.product).join(', ')||'—'} | ${g.gluts.map(p=>p.product).join(', ')||'—'} |\n`;
md+='\n## Interpretation and limits\n\nDo not replace every low-price sale with a skipped sale: selling already-produced stock still earns positive cash, and withholding it can increase the opponent’s prices. The production decision is whether to commit earlier land, seed, herd and labor to that product, conditional on expected demand and opponent supply. A price deficit can reflect production timing, delivery, market-order sequence or opponent sales; it is not automatically a sale-order bug.\n\nWheat sold may have been purchased and resold or consumed as feed. Fertilizer collected can be used rather than sold. The workbook therefore includes purchased, consumed, discarded and terminal inventory quantities, and reconciles quantities before interpreting a sales gap. Discarded means harvested/purchased stock lost from inventories, not unharvested potential yields. No-effect commands include harmless duplicate/guarded work, and do not by themselves establish the cash cost of execution failures.\n\nSources: public Kaggle episode replays and historical episode ratings; local official kaggriculture engine. Reproduction: `expand_umg_m1_fetch.py`, `extract_all_umg_animals.mjs`, `audit_all_m1_losses.py`, `summarize_all_umg_m1.mjs`. Detailed evidence: `results/fresh/all_umg_m1/`.\n';
fs.writeFileSync(path.join(root,'docs/all_umg_m1_audit.md'),md);
console.log(JSON.stringify({animals:`${games.length}/${targets.length}`,stats,groups},null,2));
