"""xopen build: assemble the exact-opening agents from the CURRENT sources (thread xopen, 2026-09-25). No games.

  agents/mgt_lead_xopen.py  = agents/mgt_lead.py verbatim + the follower core (scripts/xopen_follow.py) + the E1 glue
                              (scripts/xopen_glue_e1.py): T with an exactly replayed leader opening (configure option
                              xopen_day; -1 = off = the copied mgt_lead.py).
  agents/mgt_lpv_xopen.py   = agents/mgt_lead_deploy.py verbatim + the core + the E2 glue (scripts/xopen_glue_e2.py):
                              the deploy's exemplar followed exactly until the cash-safe date, then the deploy.
  E2 arms (same file, one XO_CFG override each): mgt_lpv_xopen_off (mode off = the deploy unchanged; harness check),
  mgt_lpv_xopen_d11 (fixed D = 11), mgt_lpv_xopen_d9 (fixed D = 9: the third shop reveal; the deploy's own day-9
  retrieval then fires), mgt_lpv_xopen_naive (tier 0, then the recorded list order), and
  mgt_lpv_xo0 = a verbatim copy of agents/mgt_lead_deploy.py (the paired baseline, same sha).
The sources are frozen under results/fresh/xopen_20260925/src/<name>_<sha12>.py; manifest: build_manifest.json.
The price path of the EV failsafe (results/fresh/xopen_20260925/price_curve.json) is embedded.

usage: .venv/Scripts/python.exe scripts/xopen_build.py [--e1-only | --e2-only] [--src-lead <frozen copy>] [--src-deploy <frozen copy>]
"""
import ast
import hashlib
import json
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTD = ROOT / "results/fresh/xopen_20260925"
CORE = ROOT / "scripts/xopen_follow.py"
GLUE1 = ROOT / "scripts/xopen_glue_e1.py"
GLUE2 = ROOT / "scripts/xopen_glue_e2.py"
E2_ARMS = {
    "mgt_lpv_xopen": {},
    "mgt_lpv_xopen_off": {"mode": "off"},
    "mgt_lpv_xopen_d11": {"dyn": False, "D_fixed": 11},
    "mgt_lpv_xopen_d9": {"dyn": False, "D_fixed": 9},
    "mgt_lpv_xopen_naive": {"failsafe": "naive"},
}


def sha(b):
    return hashlib.sha256(b).hexdigest()


SRC_OVERRIDE = {}   # --src-lead / --src-deploy <path>: build from a frozen copy instead of the live agents/ file


def read_src(name):
    p = Path(SRC_OVERRIDE[name]) if name in SRC_OVERRIDE else ROOT / "agents" / f"{name}.py"
    b = p.read_bytes()
    ast.parse(b.decode("utf-8"))
    return b, sha(b)


def core_text():
    txt = CORE.read_text(encoding="utf-8")
    curve = json.loads((OUTD / "price_curve.json").read_text(encoding="utf-8"))["curve"]
    key = "_XO_PRICE_CURVE = None\n"
    assert txt.count(key) == 1
    return txt.replace(key, "_XO_PRICE_CURVE = " + json.dumps(curve, separators=(",", ":")) + "   # embedded by scripts/xopen_build.py\n")


def last_callable_name(src):
    """the name Kaggle's loader calls: the last NEW module-level name bound to a function / class (insertion order)."""
    tree = ast.parse(src)
    order = []
    for node in tree.body:
        names = []
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            names = [node.name]
        for n in names:
            if n not in order:
                order.append(n)
    return order[-1] if order else None


def build_e1(man):
    b, h = read_src("mgt_lead")
    (OUTD / "src").mkdir(parents=True, exist_ok=True)
    (OUTD / "src" / f"mgt_lead_{h[:12]}.py").write_bytes(b)
    head = ("# mgt_lead_xopen: GENERATED by scripts/xopen_build.py (%s). Do not edit; rebuild.\n"
            "# = agents/mgt_lead.py verbatim (sha256 %s; frozen copy results/fresh/xopen_20260925/src/mgt_lead_%s.py)\n"
            "#   + the xopen follower core (scripts/xopen_follow.py) + the E1 glue (scripts/xopen_glue_e1.py):\n"
            "#   configure(sem, xopen_day=D, xopen_rule='fixed'|'dynamic', ...) replays the leader's own tape exactly\n"
            "#   until day D, then T (the code below, unchanged) plays; xopen_day=-1 (default) = the copied mgt_lead.py.\n"
            % (time.strftime("%Y-%m-%d %H:%M"), h, h[:12]))
    src = b.decode("utf-8")
    if not src.endswith("\n"):
        src += "\n"
    out = head + src + "\n\n" + core_text() + "\n\n" + GLUE1.read_text(encoding="utf-8")
    ast.parse(out)
    entry = last_callable_name(out)
    assert entry == "mgt_lead_xopen_agent", entry
    (ROOT / "agents/mgt_lead_xopen.py").write_text(out, encoding="utf-8", newline="\n")
    man["mgt_lead_xopen"] = dict(source="agents/mgt_lead.py", source_sha256=h, entry=entry,
                                 sha256=sha((ROOT / "agents/mgt_lead_xopen.py").read_bytes()),
                                 core_sha256=sha(CORE.read_bytes()), glue_sha256=sha(GLUE1.read_bytes()))
    print("agents/mgt_lead_xopen.py  <- agents/mgt_lead.py", h[:16], "entry", entry)


def build_e2(man):
    b, h = read_src("mgt_lead_deploy")
    (OUTD / "src").mkdir(parents=True, exist_ok=True)
    (OUTD / "src" / f"mgt_lead_deploy_{h[:12]}.py").write_bytes(b)
    (ROOT / "agents/mgt_lpv_xo0.py").write_bytes(b)
    man["mgt_lpv_xo0"] = dict(source="agents/mgt_lead_deploy.py", source_sha256=h, sha256=h, verbatim=True)
    src = b.decode("utf-8")
    if not src.endswith("\n"):
        src += "\n"
    core = core_text()
    glue = GLUE2.read_text(encoding="utf-8")
    tag = "XO_CFG.update({})   # __XO_VARIANT__"
    assert glue.count(tag) == 1
    for name, ov in E2_ARMS.items():
        head = ("# %s: GENERATED by scripts/xopen_build.py (%s). Do not edit; rebuild.\n"
                "# = agents/mgt_lead_deploy.py verbatim (sha256 %s; frozen copy results/fresh/xopen_20260925/src/"
                "mgt_lead_deploy_%s.py)\n"
                "#   + the xopen follower core (scripts/xopen_follow.py) + the E2 glue (scripts/xopen_glue_e2.py);\n"
                "#   arm overrides: %s. Entry (last callable): mgt_lpv_xopen_agent.\n"
                % (name, time.strftime("%Y-%m-%d %H:%M"), h, h[:12], json.dumps(ov) if ov else "none (the default arm)"))
        g = glue.replace(tag, "XO_CFG.update(%r)   # arm overrides (scripts/xopen_build.py)" % (ov,))
        out = head + src + "\n\n" + core + "\n\n" + g
        ast.parse(out)
        entry = last_callable_name(out)
        assert entry == "mgt_lpv_xopen_agent", entry
        p = ROOT / "agents" / f"{name}.py"
        p.write_text(out, encoding="utf-8", newline="\n")
        man[name] = dict(source="agents/mgt_lead_deploy.py", source_sha256=h, entry=entry, overrides=ov,
                         sha256=sha(p.read_bytes()), core_sha256=sha(CORE.read_bytes()), glue_sha256=sha(GLUE2.read_bytes()))
        print("agents/%s.py <- agents/mgt_lead_deploy.py %s entry %s %s" % (name, h[:16], entry, ov))


def main():
    for flag, name in (("--src-lead", "mgt_lead"), ("--src-deploy", "mgt_lead_deploy")):
        if flag in sys.argv:
            SRC_OVERRIDE[name] = str((ROOT / sys.argv[sys.argv.index(flag) + 1]).resolve())
    mp = OUTD / "build_manifest.json"
    man = json.loads(mp.read_text(encoding="utf-8")) if mp.exists() else {}
    if "--e2-only" not in sys.argv:
        build_e1(man)
    if "--e1-only" not in sys.argv:
        build_e2(man)
    man["built"] = time.strftime("%Y-%m-%d %H:%M:%S")
    mp.write_text(json.dumps(man, indent=1), encoding="utf-8")


if __name__ == "__main__":
    main()
